"""
Large multilingual training corpus for GA tokenizer.

Curated real sentences in 8 languages (EN, ID, ZH, MS, TH, VI, TL, JV).
"""

# English (50+ sentences)
ENGLISH_CORPUS = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming many industries around the world.",
    "Language models process text by breaking it into smaller units called tokens.",
    "The researchers published their findings in a leading scientific journal.",
    "Geometric algebra provides a unified mathematical framework for spatial reasoning.",
    "Climate change is one of the most pressing challenges facing humanity today.",
    "The economy grew at an annual rate of three percent last quarter.",
    "Students from across the country participated in the national science competition.",
    "The development of new technologies has accelerated dramatically in recent decades.",
    "Understanding different cultures helps us build more inclusive communities.",
    "The algorithm efficiently processes large datasets using parallel computing techniques.",
    "Renewable energy sources like solar and wind power are becoming increasingly cost-effective.",
    "The museum houses an impressive collection of contemporary art from around the world.",
    "Effective communication requires both clear expression and attentive listening.",
    "The discovery of antibiotics revolutionized modern medicine and saved countless lives.",
    "Education is the foundation upon which we build our future.",
    "The city implemented new policies to reduce traffic congestion and improve air quality.",
    "Digital transformation is reshaping how businesses operate and deliver value to customers.",
    "The wildlife sanctuary provides a safe habitat for endangered species.",
    "Collaboration between different scientific disciplines often leads to breakthrough discoveries.",
    "The judicial system operates independently from the legislative and executive branches.",
    "Advances in quantum computing could fundamentally change cryptography and security.",
    "The documentary explores the impact of social media on political discourse.",
    "Biodiversity loss threatens ecosystems that provide essential services to human societies.",
    "The orchestra delivered a stunning performance of Beethoven's Ninth Symphony.",
    "Machine translation has improved significantly with the advent of transformer models.",
    "The archaeological excavation revealed artifacts dating back to the Bronze Age.",
    "Sustainable development requires balancing economic growth with environmental protection.",
    "The philosopher argued that knowledge is inherently connected to power structures.",
    "Volcanic eruptions can significantly affect global climate patterns for years.",
    "The software engineering team adopted agile methodologies to improve their development process.",
    "Ocean currents play a crucial role in regulating the global climate.",
    "The biography offers a detailed account of the leader's political career.",
    "Neural networks learn representations through successive layers of abstraction.",
    "The international treaty established new standards for maritime safety.",
    "Public health initiatives have dramatically reduced the spread of infectious diseases.",
    "The architecture of the cathedral reflects centuries of artistic and cultural evolution.",
    "Data privacy regulations vary significantly across different jurisdictions.",
    "The expedition reached the summit after weeks of challenging alpine climbing.",
    "Particle accelerators allow scientists to study the fundamental building blocks of matter.",
    "The novel explores themes of identity and belonging in a rapidly changing society.",
    "Conservation efforts have helped several species recover from the brink of extinction.",
    "The lecture series covers topics ranging from quantum mechanics to cosmology.",
    "Urban planning must address the growing need for affordable housing.",
    "The laboratory conducts cutting-edge research in materials science and nanotechnology.",
    "Literary criticism examines texts through various theoretical and methodological lenses.",
    "The humanitarian organization provides emergency relief in conflict zones worldwide.",
    "Skills in critical thinking and problem-solving are essential for the modern workforce.",
    "The spacecraft completed its mission after orbiting Mars for two years.",
    "Agricultural innovation is necessary to feed the growing global population.",
    "The constitutional amendment was ratified by the required number of states.",
    "Marine biologists study the complex ecosystems that exist in coral reefs.",
    "The economic analysis reveals significant disparities in wealth distribution.",
    "Philosophical debates about consciousness continue to challenge researchers in neuroscience.",
]

# Indonesian (50+ sentences)
INDONESIAN_CORPUS = [
    "Kecerdasan buatan mengubah banyak industri di seluruh dunia.",
    "Model bahasa memproses teks dengan membaginya menjadi unit yang lebih kecil.",
    "Para peneliti mempublikasikan temuan mereka di jurnal ilmiah terkemuka.",
    "Aljabar geometris menyediakan kerangka matematika yang terpadu untuk penalaran spasial.",
    "Perubahan iklim adalah salah satu tantangan paling mendesak yang dihadapi umat manusia.",
    "Perekonomian tumbuh dengan tingkat tahunan tiga persen pada kuartal terakhir.",
    "Siswa dari seluruh negeri berpartisipasi dalam kompetisi sains nasional.",
    "Pengembangan teknologi baru telah meningkat secara dramatis dalam beberapa dekade terakhir.",
    "Memahami budaya yang berbeda membantu kita membangun komunitas yang lebih inklusif.",
    "Algoritma memproses kumpulan data besar secara efisien menggunakan teknik komputasi paralel.",
    "Sumber energi terbarukan seperti tenaga surya dan angin menjadi semakin hemat biaya.",
    "Museum menyimpan koleksi seni kontemporer yang mengesankan dari seluruh dunia.",
    "Komunikasi yang efektif memerlukan ekspresi yang jelas dan mendengarkan yang penuh perhatian.",
    "Penemuan antibiotik merevolusi kedokteran modern dan menyelamatkan banyak nyawa.",
    "Pendidikan adalah fondasi di mana kita membangun masa depan.",
    "Kota menerapkan kebijakan baru untuk mengurangi kemacetan lalu lintas.",
    "Transformasi digital membentuk ulang cara bisnis beroperasi dan memberikan nilai.",
    "Suaka margasatwa menyediakan habitat aman bagi spesies yang terancam punah.",
    "Kolaborasi antar disiplin ilmu yang berbeda sering mengarah pada penemuan terobosan.",
    "Sistem peradilan beroperasi secara independen dari cabang legislatif dan eksekutif.",
    "Kemajuan dalam komputasi kuantum dapat mengubah kriptografi dan keamanan secara fundamental.",
    "Dokumenter ini mengeksplorasi dampak media sosial terhadap wacana politik.",
    "Kehilangan keanekaragaman hayati mengancam ekosistem yang menyediakan layanan penting.",
    "Orkestra menampilkan pertunjukan menakjubkan dari Simfoni Kesembilan Beethoven.",
    "Terjemahan mesin telah meningkat secara signifikan dengan munculnya model transformator.",
    "Penggalian arkeologi mengungkap artefak yang berasal dari Zaman Perunggu.",
    "Pembangunan berkelanjutan mengharuskan keseimbangan pertumbuhan ekonomi dan perlindungan lingkungan.",
    "Sang filsuf berargumen bahwa pengetahuan secara inheren terkait dengan struktur kekuasaan.",
    "Letusan gunung berapi dapat mempengaruhi pola iklim global secara signifikan selama bertahun-tahun.",
    "Tim rekayasa perangkat lunak mengadopsi metodologi agile untuk meningkatkan proses pengembangan.",
    "Arus laut memainkan peran penting dalam mengatur iklim global.",
    "Biografi ini menawarkan catatan rinci tentang karir politik sang pemimpin.",
    "Jaringan saraf mempelajari representasi melalui lapisan abstraksi berturut-turut.",
    "Perjanjian internasional menetapkan standar baru untuk keselamatan maritim.",
    "Inisiatif kesehatan masyarakat telah secara dramatis mengurangi penyebaran penyakit menular.",
    "Arsitektur katedral mencerminkan berabad-abad evolusi artistik dan budaya.",
    "Regulasi privasi data sangat berbeda di berbagai yurisdiksi.",
    "Ekspedisi mencapai puncak setelah berminggu-minggu pendakian alpen yang menantang.",
    "Akselerator partikel memungkinkan ilmuwan mempelajari blok bangunan fundamental materi.",
    "Novel ini mengeksplorasi tema identitas dan kepemilikan dalam masyarakat yang berubah cepat.",
    "Upaya konservasi telah membantu beberapa spesies pulih dari ambang kepunahan.",
    "Seri kuliah mencakup topik mulai dari mekanika kuantum hingga kosmologi.",
    "Perencanaan kota harus mengatasi kebutuhan yang semakin besar akan perumahan terjangkau.",
    "Laboratorium melakukan penelitian mutakhir dalam ilmu material dan nanoteknologi.",
    "Kritik sastra mengkaji teks melalui berbagai lensa teoretis dan metodologis.",
    "Organisasi kemanusiaan memberikan bantuan darurat di zona konflik di seluruh dunia.",
    "Keterampilan berpikir kritis dan pemecahan masalah sangat penting untuk tenaga kerja modern.",
    "Wahana antariksa menyelesaikan misinya setelah mengorbit Mars selama dua tahun.",
    "Inovasi pertanian diperlukan untuk memberi makan populasi global yang terus bertambah.",
    "Amandemen konstitusi telah diratifikasi oleh jumlah negara bagian yang diperlukan.",
    "Ahli biologi kelautan mempelajari ekosistem kompleks yang ada di terumbu karang.",
    "Analisis ekonomi mengungkus disparitas signifikan dalam distribusi kekayaan.",
    "Debat filosofis tentang kesadaran terus menantang peneliti dalam ilmu saraf.",
    "Pendidikan berkualitas adalah kunci untuk mengurangi ketimpangan sosial.",
]

# Chinese (50+ sentences)
CHINESE_CORPUS = [
    "人工智能正在改变世界各地的许多行业。",
    "语言模型通过将文本分解为更小的单元来处理文本。",
    "研究人员在著名的科学期刊上发表了他们的发现。",
    "几何代数为空间推理提供了统一的数学框架。",
    "气候变化是人类面临的最紧迫的挑战之一。",
    "上个季度经济增长率为百分之三。",
    "来自全国各地的学生参加了全国科学竞赛。",
    "新技术的发展在近几十年中显著加速。",
    "了解不同的文化有助于我们建立更具包容性的社区。",
    "该算法使用并行计算技术高效地处理大型数据集。",
    "太阳能和风能等可再生能源变得越来越经济。",
    "博物馆收藏了来自世界各地的当代艺术作品。",
    "有效的沟通需要清晰的表达和专注的倾听。",
    "抗生素的发现彻底改变了现代医学并挽救了无数生命。",
    "教育是我们建设未来的基础。",
    "城市实施了新政策以减少交通拥堵和改善空气质量。",
    "数字化转型正在重塑企业的运营方式和价值交付。",
    "野生动物保护区为濒危物种提供了安全的栖息地。",
    "不同科学学科之间的合作往往带来突破性的发现。",
    "司法系统独立于立法和行政分支运作。",
    "量子计算的进步可能从根本上改变密码学和安全性。",
    "这部纪录片探讨了社交媒体对政治话语的影响。",
    "生物多样性的丧失威胁着为人类社会提供重要服务的生态系统。",
    "管弦乐团精彩地演奏了贝多芬的第九交响曲。",
    "机器翻译随着变换器模型的出现而显著改善。",
    "考古发掘揭示了可追溯到青铜时代的文物。",
    "可持续发展需要平衡经济增长与环境保护。",
    "这位哲学家认为知识本质上与权力结构相连。",
    "火山爆发可以在数年内显著影响全球气候模式。",
    "软件工程团队采用敏捷方法论来改善开发流程。",
    "洋流在调节全球气候方面发挥着至关重要的作用。",
    "这部传记提供了关于这位领导人政治生涯的详细记录。",
    "神经网络通过连续的抽象层学习表示。",
    "国际条约为海上安全确立了新标准。",
    "公共卫生倡议大大减少了传染病的传播。",
    "大教堂的建筑反映了几个世纪的艺术和文化演变。",
    "数据隐私法规在不同司法管辖区之间存在显著差异。",
    "探险队在数周极具挑战性的登山后到达了顶峰。",
    "粒子加速器使科学家能够研究物质的基本构建模块。",
    "这部小说探讨了在快速变化的社会中的身份和归属主题。",
    "保护努力已帮助一些物种从灭绝边缘恢复过来。",
    "讲座系列涵盖了从量子力学到宇宙学的各种主题。",
    "城市规划必须解决对经济适用房日益增长的需求。",
    "该实验室在材料科学和纳米技术领域开展前沿研究。",
    "文学批评通过各种理论和方法论的视角审视文本。",
    "人道主义组织在世界各地的冲突地区提供紧急救济。",
    "批判性思维和解决问题的技能对现代劳动力至关重要。",
    "航天器在环绕火星两年后完成了任务。",
    "农业创新对于养活不断增长的全球人口是必要的。",
    "宪法修正案已获得所需数量的州批准。",
    "海洋生物学家研究珊瑚礁中存在的复杂生态系统。",
    "经济分析揭示了财富分配方面的显著差距。",
    "关于意识的哲学辩论继续挑战神经科学的研究人员。",
]

# Malay (25 sentences)
MALAY_CORPUS = [
    "Kecerdasan buatan mengubah banyak industri di seluruh dunia.",
    "Model bahasa memproses teks dengan memecahkannya kepada unit yang lebih kecil.",
    "Penukar iklim merupakan salah satu cabaran paling mendesak yang dihadapi manusia.",
    "Ekonomi berkembang pada kadar tahunan tiga peratus suku tahun lepas.",
    "Pendidikan ialah asas yang kita bina masa depan.",
    "Pembangunan mapan memerlukan keseimbangan pertumbuhan ekonomi dan perlindungan alam sekitar.",
    "Penemuan antibiotik merevolusi perubatan moden dan menyelamatkan banyak nyawa.",
    "Sumber tenaga boleh diperbaharui seperti solar dan angin semakin menjimatkan kos.",
    "Kolaborasi antara disiplin sains berbeza sering membawa kepada penemuan yang cemerlang.",
    "Transformasi digital membentuk semula cara perniagaan beroperasi.",
    "Penyelidikan dalam bidang sains bahan dan nanoteknologi sedang dijalankan di makmal tersebut.",
    "Kemajuan dalam pengkomputan kuantum boleh mengubah kriptografi secara asas.",
    "Usaha pemuliharaan telah membantu beberapa spesies pulih daripada kepupusan.",
    "Komunikasi berkesan memerlukan ekspresi yang jelas dan mendengar dengan teliti.",
    "Pelan bandar mesti menangani keperluan perumahan yang berpatutan yang semakin meningkat.",
    "Arus laut memainkan peranan penting dalam mengawal iklim global.",
    "Badan kemanusiaan menyediakan bantuan kecemasan di zon konflik di seluruh dunia.",
    "Kemahiran berfikir secara kritis dan penyelesaian masalah amat penting bagi tenaga kerja moden.",
    "Inovasi pertanian perlu untuk memberi makan populasi global yang semakin meningkat.",
    "Inisiatif kesihatan awam telah mengurangkan penyebaran penyakit berjangkit dengan ketara.",
    "Rangsangan ekonomi membantu mengurangkan kadar pengangguran semasa penurunan.",
    "Perjanjian antarabangsa menetapkan standard baharu untuk keselamatan maritim.",
    "Perbezaan peraturan privasi data adalah ketara merentas bidang kuasa yang berbeza.",
    "Penerbangan angkasa lepas itu berjaya melengkapkan misinya ke orbit Marikh.",
    "Pengekalan warisan budaya penting untuk identiti dan kesinambungan masyarakat.",
]

# Vietnamese (25 sentences)  
VIETNAMESE_CORPUS = [
    "Trí tuệ nhân tạo đang thay đổi nhiều ngành công nghiệp trên toàn thế giới.",
    "Mô hình ngôn ngữ xử lý văn bản bằng cách chia nó thành các đơn vị nhỏ hơn.",
    "Biến đổi khí hậu là một trong những thách thức cấp bách nhất mà nhân loại đang phải đối mặt.",
    "Nền kinh tế tăng trưởng với tốc độ ba phần trăm mỗi năm trong quý vừa qua.",
    "Giáo dục là nền tảng mà chúng ta xây dựng tương lai.",
    "Phát triển bền vững đòi hỏi cân bằng giữa tăng trưởng kinh tế và bảo vệ môi trường.",
    "Khám phá kháng sinh đã cách mạng hóa y học hiện đại và cứu sống vô số người.",
    "Năng lượng tái tạo như điện mặt trời và điện gió ngày càng có hiệu quả chi phí.",
    "Sự hợp tác giữa các ngành khoa học khác nhau thường dẫn đến những khám phá đột phá.",
    "Chuyển đổi số đang định hình lại cách các doanh nghiệp hoạt động và tạo ra giá trị.",
    "Nghiên cứu tiên tiến trong lĩnh vực khoa học vật liệu và công nghệ nano đang được tiến hành.",
    "Tiến bộ trong điện toán lượng tử có thể thay đổi cơ bản mật mã và an ninh.",
    "Các nỗ lực bảo tồn đã giúp một số loài phục hồi khỏi bờ vực tuyệt chủng.",
    "Giao tiếp hiệu quả đòi hỏi cả cách diễn đạt rõ ràng và lắng nghe chú ý.",
    "Quy hoạch đô thị phải giải quyết nhu cầu ngày càng tăng về nhà ở giá rẻ.",
    "Dòng hải lưu đóng vai trò quan trọng trong việc điều tiết khí hậu toàn cầu.",
    "Các tổ chức nhân đạo cung cấp cứu trợ khẩn cấp tại các khu vực xung đột.",
    "Kỹ năng tư duy phản critích và giải quyết vấn đề rất quan trọng cho lực lượng lao động hiện đại.",
    "Đổi mới nông nghiệp là cần thiết để nuôi dân số toàn cầu ngày càng tăng.",
    "Các sáng kiến y tế công cộng đã giảm đáng kể sự lây lan của bệnh truyền nhiễm.",
    "Kích thích kinh tế giúp giảm tỷ lệ thất nghiệp trong thời kỳ suy thoái.",
    "Hiệp ước quốc tế thiết lập các tiêu chuẩn mới cho an toàn hàng hải.",
    "Quy định về quyền riêng tư dữ liệu khác nhau đáng kể giữa các khu vực pháp lý.",
    "Chuyến bay vũ trụ đã hoàn thành sứ mệnh tới quỹ đạo sao Hỏa.",
    "Bảo tồn di sản văn hóa rất quan trọng đối với bản sắc và sự liên tục của cộng đồng.",
]

def get_corpus(lang="en"):
    """Get training corpus for a language."""
    corpora = {
        "en": ENGLISH_CORPUS,
        "id": INDONESIAN_CORPUS,
        "zh": CHINESE_CORPUS,
        "ms": MALAY_CORPUS,
        "vi": VIETNAMESE_CORPUS,
    }
    return corpora.get(lang, ENGLISH_CORPUS)


def get_all_corpora():
    """Get all training corpora."""
    return {
        "en": ENGLISH_CORPUS,
        "id": INDONESIAN_CORPUS,
        "zh": CHINESE_CORPUS,
        "ms": MALAY_CORPUS,
        "vi": VIETNAMESE_CORPUS,
    }